version: 0.2
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket elevate-pipeline-deploy --output-template-file compiledSamTemplate.yaml
artifacts:
  type: zip
  files:
    - compiledSamTemplate.yaml